"""add dsm fields

Revision ID: b3ba4148173e
Revises: e00775a1324d
Create Date: 2026-04-23 13:24:36.488732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3ba4148173e'
down_revision: Union[str, Sequence[str], None] = 'e00775a1324d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessments', sa.Column('category', sa.String(), nullable=True))
    op.add_column('assessments', sa.Column('subcategory', sa.String(), nullable=True))
    op.add_column('assessments', sa.Column('disorder', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assessments', 'disorder')
    op.drop_column('assessments', 'subcategory')
    op.drop_column('assessments', 'category')
    # ### end Alembic commands ###
